### ISSUE TITLE
Add more calendar colours

### ISSUE THREAD

**Issue by huy-ta** [OpenPaaS-Suite/esn-frontend-calendar#109]
#### Steps to find the feature

1. Go to the Calendar SPA
2. Open the menu to create a new calendar

#### Current behaviour

There are only a few fixed colours for the new calendar.

![CalendarColors](https://user-images.githubusercontent.com/24670327/93728970-a0fcd800-fbec-11ea-9b38-d4c5478752f8.png)

#### Wanted behaviour

There should be much more colours, ideally we should have a colour picker to let the user chooses freely.

**Comment by pbson** [comment]
DoD
**What I have done**

I've fixed the issue https://github.com/OpenPaaS-Suite/esn-frontend-calendar/issues/109. Now the user is allow to choose a custom color for their calendar instead of those default one.

**Environment tested**

- Browser: Firefox, Chrome (Desktop - Ubuntu)
- Mode: Dev, Production
