### ISSUE TITLE
cannot see calendars if user has duplicate calendars

### ISSUE THREAD

**Issue by rezk2ll** [OpenPaaS-Suite/esn-frontend-calendar#116]
error log:
```
angular.js:11707 Error: [ngRepeat:dupes] Duplicates in a repeater are not allowed.
Use 'track by' expression to specify unique keys. 
Repeater: calendar in $ctrl.calendars track by calendar.uniqueId, Duplicate key: /calendars/5f593d3617edf70026565bba/5f593d3617edf70026565bba.json...
```

current behavior:
none of the calendars appear.
![image](https://user-images.githubusercontent.com/6764881/93792573-9d3d7580-fc2d-11ea-888d-225f9d125665.png)

**cause** : could've happened during the migration of OBM -> OpenPaaS

**expected**: user should see his calendars

**Comment by tuanlc** [comment]
A related issue that describes the consequence of this bug: https://github.com/OpenPaaS-Suite/esn-frontend-calendar/issues/108

**Comment by tuanlc** [comment]
So, by somehow (migration from OBM, synchronize from Thunderbird, multiple threads in PHP Sabre, etc), the duplicate default calendar issue is back. I propose:
1. Correct for the production by removing duplicate default calendar
2. Fix consistency issue in Sabre (It was fixed by creating a compound index but maybe some change without aware of its factors)
