### ISSUE TITLE
The calendar configuration page doesn't redirect to the calendar view after saving a modification

### ISSUE THREAD

**Issue by fabienmoyon** [OpenPaaS-Suite/esn-frontend-calendar#134]
#### CURRENTLY

![Peek 24-09-2020 14-48](https://user-images.githubusercontent.com/11298249/94148050-6ad28900-fe76-11ea-8072-2ce73b10d3e2.gif)

#### EXPECTED 

1. After a save redirect to the calendar page

1. If in the `Calendar configuration` page the `Calendar configuration` link could toggle to the to the calendar page.

![Capture d’écran de 2020-09-24 15-03-36](https://user-images.githubusercontent.com/11298249/94148635-298ea900-fe77-11ea-9061-7f7579ff506d.png)

Edit (from @huy-ta): I also propose that the "Cancel" button should be changed to "Back" (with a back arrow icon) because it doesn't cancel anything at all. There should also be a prompt to warn the user for unsaved changes. (there'll be a formal user story for this)

**Comment by huy-ta** [comment]
#### User story summary

As a user, I want a less confusing behaviour for the Calendar configuration page.

#### Criteria

- [ ] The "Cancel" button should be changed to a back arrow icon button (because it only redirects back to the main calendar page and doesn't cancel anything at all).
- [ ] After clicking the "Save" button, I should be redirected back to the main calendar page.
- [ ] If I press the back arrow icon button (currently the "Cancel" button) and there's some changes I haven't saved, there should be a prompt to warn that I have unsaved changes.
- [ ] There should be a notification when the configuration has been saved successfully.
- [ ] There should be a notification when the configuration fails to be saved.
- [ ] The "Save" button should not be active unless I have made some changes.

#### UI/UX Design

- Desktop/Laptop:

![calendar_config_desktop](https://user-images.githubusercontent.com/24670327/94399982-92856200-0192-11eb-996e-93e94339e86d.png)

- Mobile:

![calendar_config_mobile](https://user-images.githubusercontent.com/24670327/94399897-6833a480-0192-11eb-891b-502d62eb17f8.png)
