### ISSUE TITLE
As a user, I want a less confusing behaviour for the Calendar configuration page

### ISSUE THREAD

**Issue by huy-ta** [OpenPaaS-Suite/esn-frontend-calendar#143]
#### User story summary

As a user, I want a less confusing behaviour for the Calendar configuration page.

#### Criteria

- [x] The "Cancel" button should be changed to a back arrow icon button (because it only redirects back to the main calendar page and doesn't cancel anything at all).
- [x] There should be a title for the configuration page: "Manage calendars".
- [x] After clicking the "Save" button, I should be redirected back to the main calendar page.
- [ ] If I press the back arrow icon button (currently the "Cancel" button) and there's some changes I haven't saved, there should be a prompt to warn that I have unsaved changes.
- [x] There should be a notification when the configuration has been saved successfully.
- [x] There should be a notification when the configuration fails to be saved.
- [x] The "Save" button should not be active unless I have made some changes.
- [x] The toggles/switches in the "DISPLAY" tab should be replaced with checkboxes (see the screenshots below).
- [ ] (Optional) If I'm already in the Calendar configuration page, when I click "Manage calendars", I will be redirected back to the main calendar page.

#### UI/UX Design

![calendar_configuration_desktop_1](https://user-images.githubusercontent.com/24670327/94641946-eae06f00-030c-11eb-8f8f-35ab2e62ad1d.png)

![calendar_configuration_desktop_2](https://user-images.githubusercontent.com/24670327/94641949-eb790580-030c-11eb-90c7-f7ecf2fb2f6c.png)

**Comment by MichaelBailly** [comment]
Hello,
according to a customer feedback, the UI is also confusing because the left sidebar is visible, but any user action on it do not imply any (visible) change on the main screen.

One simple solution may be to hide the left sidebar when in a configuration screen. Configuration screens are:

- manage calendars
- calendar settings page (where you choose the color, the delegation, ...)

**Comment by MichaelBailly** [comment]
Display: working days and Display: Declined events right now are using toggle switch, which is highly non-understandable. I suggest:
- to use a checkbox
- to rephrase the sentence to positive mode, like "show only working days" and "Show declined events"

**Comment by huy-ta** [comment]
@MichaelBailly Thanks for your feedback, I'll change the user story accordingly.

> One simple solution may be to hide the left sidebar when in a configuration screen.

Or perhaps we can make it a dialog instead.

**Comment by huy-ta** [comment]
> Or perhaps we can make it a dialog instead.

Something like this:

![calendar_config_dialog](https://user-images.githubusercontent.com/24670327/94406889-e85f0780-019c-11eb-96f8-47b6e8c682ba.png)

**Comment by huy-ta** [comment]
@MichaelBailly As using a dialog for the calendar configuration page will require a lot of refactoring, I'll create another issue just for that. Right now we need to fix the more confusing behaviour(s) first. WDYT?

**Comment by MichaelBailly** [comment]
ok

**Comment by tuanlc** [comment]
> - [ ] If I press the back arrow icon button (currently the "Cancel" button) and there's some changes I haven't saved, there should be a prompt to warn that I have unsaved changes.

There are many places in ESN that does not have this rule, does this feature matter since the cost to implement it is not cheap. We need to detect which state that needs to be checked and what is criteria to have a promt action?

> - [ ] (Optional) If I'm already in the Calendar configuration page, when I click "Manage calendars", I will be redirected back to the main calendar page

This is a not ESN style

**Comment by tuanlc** [comment]
### Definition of Done
**Done**:
- [x] The "Cancel" button should be changed to a back arrow icon button (because it only redirects back to the main calendar page and doesn't cancel anything at all).
- [x] There should be a title for the configuration page: "Manage calendars".
- [x] After clicking the "Save" button, I should be redirected back to the main calendar page.
- [x] There should be a notification when the configuration has been saved successfully.
- [x] There should be a notification when the configuration fails to be saved.
- [x] The "Save" button should not be active unless I have made some changes.
- [x] The toggles/switches in the "DISPLAY" tab should be replaced with checkboxes (see the screenshots below).

**Won't do**:
- [ ] (Optional) If I'm already in the Calendar configuration page, when I click "Manage calendars", I will be redirected back to the main calendar page.
- [ ] If I press the back arrow icon button (currently the "Cancel" button) and there's some changes I haven't saved, there should be a prompt to warn that I have unsaved changes.

Reason: https://github.com/OpenPaaS-Suite/esn-frontend-calendar/issues/143#issuecomment-704787470

**Comment by fabienmoyon** [comment]
@huy-ta maybe it's too late but please use the same modal look as in esn : 

![Capture d’écran de 2020-10-08 11-22-01](https://user-images.githubusercontent.com/11298249/95441963-14c41200-095b-11eb-92d7-c1741f32c90b.png)

![94243166-3c6db000-ff41-11ea-8328-e092e261915c](https://user-images.githubusercontent.com/11298249/95441988-1ab9f300-095b-11eb-9102-b54ae1a6f356.png)


</details>
