### ISSUE TITLE
Event details are not correct in email sent to attendees when organizer edit details of a recurrence

### ISSUE THREAD

**Issue by hantt12** [OpenPaaS-Suite/esn-frontend-calendar#154]
Steps to reproduce:

1. Create a repeated event with attendees

2. Edit details of a random recurrence in the series (title, time...)

3. As an attendee, check the email in the inbox

Expected result:

Attendee receives email with the updated information (both in bluebar and in email content)

Actual result:

Email still shows old details

**Comment by piavgh** [comment]
After investigating this issue, I note what I found here:

The reason for this issue is: When an exceptional event is updated, the `event` parameter (which is sent from Sabre to ESN) contains the old information

Check this line: https://ci.linagora.com/linagora/lgs/openpaas/esn-sabre/blob/master/lib/CalDAV/Schedule/IMipPlugin.php#L134

I guess we will need to fix the `$eventMessage` before sending to ESN

I will unassign and let the calendar team fix this in Sabre

**Comment by asmaNode** [comment]
DEMO :
https://streamable.com/dhkkei

**Comment by MichaelBailly** [comment]
Please can we have another demo:

1/ you create a daily event starting on Monday Oct 19, you invite userX
2/ you change the time of the event of Oct 20
3/ you change the time of the event of Oct 21
4/ you change the time of the event of Oct 20
5/ check that userX last received email is about the change 4/

Thanks

**Comment by asmaNode** [comment]
@MichaelBailly  https://streamable.com/r690i6

**Comment by MichaelBailly** [comment]
Thanks. I'm a little afraid by this trick... By the way @asmaNode you know you can  change an event time by drag'n'dropping it, it's way faster :-)

**Comment by asmaNode** [comment]
yes i already know it ;p , just to be more clear in my demonstration

**Comment by renaudboyer** [comment]
@MichaelBailly Sabre send a message with Master event and exceptions and with updated VEVENT at the end of the message, so picking the last event of the list works better than the previous code that was picking the first one of the list.
But it's still a quick fix while waiting to the modification of the Sabre notification call.

**Comment by huy-ta** [comment]
Closed this in favour of https://github.com/OpenPaaS-Suite/esn-frontend-calendar/issues/206.
