### ISSUE TITLE
As a user, I want to have a visual hint when using the up/down arrow buttons to select an attendee or resource from the autocomplete dropdown

### ISSUE THREAD

**Issue by huy-ta** [OpenPaaS-Suite/esn-frontend-calendar#174]
#### User story summary

As a user, I want to have a visual hint when using the up/down arrow buttons to select an attendee or resource from the autocomplete dropdown.

#### Where to find the feature

- Log in and go to Calendar
- Choose to create a new event, and the event dialog should appear
- Select the "Attendees" field, try entering an email or username
- The autocomplete dropdown should appear

#### Criteria

- [x] I can select an item from the autocomplete dropdown by using the up/down arrow buttons on my keyboard and pressing 'Enter'.
- [x] When I press the up/down arrow buttons, there should be a visual hint (see the first picture below) to indicate which item is being selected.

#### UI/UX Design

- This is how the visual hint mentioned above should look like (a background with a greyish color):

![autocomplete-dropdown-indicator](https://user-images.githubusercontent.com/24670327/95286721-49b66300-088e-11eb-8ce9-8c341e39ee62.png)

**Comment by tuanlc** [comment]
### Definition of Done

**Done**: 
- [x] I can select an item from the autocomplete dropdown by using the up/down arrow buttons on my keyboard and pressing 'Enter'.
- [x] When I press the up/down arrow buttons, there should be a visual hint (see the first picture below) to indicate which item is being selected.

**Demo**:
Calendar :calendar: 
![calendar](https://user-images.githubusercontent.com/7950991/95448791-10651c80-098e-11eb-9b5b-f3048a3e5184.gif)

Inbox :inbox_tray: 
![inbox](https://user-images.githubusercontent.com/7950991/95448867-2b379100-098e-11eb-84cf-0a5bdb1d4802.gif)

**Impact**: All the autocomplete inputs for all SPAs (Users, Resources, Contacts, Groups, etc)

**To testing**: 
- The fix was deployed to dev.open-paas.org/calendar/
- On productioni will be deployed in the comming weeks
