### ISSUE TITLE
[EPIC] Redesigning event notification emails

### ISSUE THREAD

**Issue by huy-ta** [OpenPaaS-Suite/esn-frontend-calendar#234]
#### Stories

- Event invitation emails: https://github.com/OpenPaaS-Suite/esn-frontend-calendar/issues/235
- Event update emails: https://github.com/OpenPaaS-Suite/esn-frontend-calendar/issues/261
- Event cancellation emails: https://github.com/OpenPaaS-Suite/esn-frontend-calendar/issues/262
- Event acceptance emails: https://github.com/OpenPaaS-Suite/esn-frontend-calendar/issues/237
- Event tentative acceptance emails: https://github.com/OpenPaaS-Suite/esn-frontend-calendar/issues/263
- Event decline emails: https://github.com/OpenPaaS-Suite/esn-frontend-calendar/issues/238
- Event alarm emails: https://github.com/OpenPaaS-Suite/esn-frontend-calendar/issues/264
- Propose new time emails: https://github.com/OpenPaaS-Suite/esn-frontend-calendar/issues/364
- Resource booking emails: https://github.com/OpenPaaS-Suite/esn-frontend-calendar/issues/365
- Resource acceptance emails: https://github.com/OpenPaaS-Suite/esn-frontend-calendar/issues/366
- Resource decline emails: https://github.com/OpenPaaS-Suite/esn-frontend-calendar/issues/367
- Event update details: https://github.com/OpenPaaS-Suite/esn-frontend-calendar/issues/447

#### Notes

- Please take a look at the PRs that implemented the previous new email templates:
  - https://ci.linagora.com/linagora/lgs/openpaas/esn/merge_requests/1318
  - https://ci.linagora.com/linagora/lgs/openpaas/linagora.esn.calendar/merge_requests/687

**Comment by hantt12** [comment]
Update status:
- Invitation/event update: bug https://github.com/OpenPaaS-Suite/esn-frontend-calendar/issues/486
- Event cancellation: OK
- Accept/Decline/Maybe: bug https://github.com/OpenPaaS-Suite/esn-frontend-calendar/issues/484
- Reminder (alarm): bug https://github.com/OpenPaaS-Suite/esn-frontend-calendar/issues/483
- Propose new time: OK
- Resource related emails: Not tested yet because  I am unable to create go to admin site to create resource. I will test later
