### ISSUE TITLE
mobile/Save button is not visible when user edits event

### ISSUE THREAD

**Issue by hantt12** [OpenPaaS-Suite/esn-frontend-calendar#245]
Steps to reproduce:
Use mobile phone device with Chrome or Safari

1. Create an event
2. Click on that event and try to edit the event name

=> The form is zoomed and Save button is not visible

https://streamable.com/qe9smu

**Comment by huy-ta** [comment]
Note that the issue only happens in iOS mobile devices.

**Comment by huy-ta** [comment]
This is a feature of Webkit-based browsers (basically all browsers in iOS). It forces the screen to zoom in when the user selects an input with a font size less than 16px. The "SAVE" button is not gone forever because the user can just zoom out for it to be visible again. This can be a little bit inconvenient, but it is not a bug.
