### ISSUE TITLE
"Propose new time" option in bluebar does not work

### ISSUE THREAD

**Issue by hantt12** [OpenPaaS-Suite/esn-frontend-calendar#254]
Steps: 

1. User A invites user B to an event
2. User B opens the invitation email
3. User B clicks on Propose New Time  in bluebar

Expected result:
Allow users to propose new time

Actual result:
Nothing happens

**Comment by rezk2ll** [comment]
this was happening when `webpack` uglifies the code, what happens is the `$modal` can't find the controller dependency because it was declared as

```js
 $modal({
        template: require('./event-date-suggestion-modal.pug'),
        resolve: {
          event: function() {
            return event.clone();
          }
        },
        controller: function($scope, event) { // <- bug here
....
```

![image](https://user-images.githubusercontent.com/6764881/100762617-7a30fe00-33f4-11eb-84bb-7c457e3c6f87.png)

can be solved using [nginject-loader](https://github.com/bholloway/nginject-loader)

**Comment by tlle14** [comment]
Thank @huy-ta 
Retest failed.
The form displays but the default time is not correct. 
![image](https://user-images.githubusercontent.com/69950655/100822184-6634dd00-3484-11eb-8d1a-c664b86d92fd.png)

Expected: Default time should be the time of the event

**Comment by tlle14** [comment]
CC: @rezk2ll

**Comment by rezk2ll** [comment]
# Definition of Done

### dev done
resolved the issue in https://github.com/OpenPaaS-Suite/esn-frontend-calendar/pull/321

### env
OS: `Ubuntu 18.04 LTS`
browser: `chrome  87.0.4280.141`
