### ISSUE TITLE
Mobile > 3 days view displays incorrectly when there's only 3 working days per week

### ISSUE THREAD

**Issue by tlle14** [OpenPaaS-Suite/esn-frontend-calendar#295]
# Precondition
Setting working days are: mon - wed - fri
Setting display for the calendar: hide non-working day
![IMG_0004](https://user-images.githubusercontent.com/69950655/100434815-a33d5000-30cf-11eb-87e5-f3536af6c0d0.PNG)
![IMG_0005](https://user-images.githubusercontent.com/69950655/100434824-a8020400-30cf-11eb-9d03-98a03b998987.PNG)

# Actual Result
On a mobile view, `3 days` mode is displaying incorrectly. The week is split into 2 parts: Monday+Wednesday and Friday

![IMG_0002](https://user-images.githubusercontent.com/69950655/100434950-d67fdf00-30cf-11eb-9b24-7fe7d6d41af4.PNG)
![IMG_0003](https://user-images.githubusercontent.com/69950655/100434960-d849a280-30cf-11eb-8035-b1bd517a69dc.PNG)

# Expected Result
Should display correctly 3 working days of the week.

# Environment
DEV environment
- Android: Samsung A51, Android 10, Chrome
- iOS: iphone 11 Pro Max, iOS 14.0, Safari

**Comment by asmaNode** [comment]
-The way of how the days is displayed on mobile is not a bug , the issue is that the default view of fullcalendar is three days view on mobile ( for that we have a devided days).

-If we change the view to week (all the days will be displayed)
-So what i propose (this issue will not be a bug , the user must change the view)
-or we change the default view automatically on mobile from three days to week 
@tlle14 @huy-ta @renaudboyer

**Comment by huy-ta** [comment]
> the issue is that the default view of fullcalendar is three days view on mobile

Then why does it display as two days?

**Comment by asmaNode** [comment]
There is a problem with fullcalendar , when displaying it in mobile , the default preview is three days , but for UX reasons the days is devided ,
To show all working days we just choose week view for this , so there is no need to resolve this one as long the functionality exists
**Please check the demo for more details**
https://images.zenhubusercontent.com/276895569/ce14f322-1870-4155-86c1-6243bad91821/3daysdisplay.mp4
