### ISSUE TITLE
Import menu entry does not work

### ISSUE THREAD

**Issue by MichaelBailly** [OpenPaaS-Suite/esn-frontend-calendar#51]
The calendar (+) button -> **Import** does not work.

Error in the console:
```
angular-strap.js:2501 Error: [$injector:unpr] Unknown provider: davImportServiceProvider <- davImportService <- CalCalendarImportController
http://errors.angularjs.org/1.3.20/$injector/unpr?p0=davImportServiceProvider%20%3C-%20davImportService%20%3C-%20CalCalendarImportController
```

**Comment by huy-ta** [comment]
This issue is caused by the fact that the `davImportService` is defined in `linagora.esn.dav.import`, which now only resides inside the `esn-frontend-contacts` repo: https://github.com/OpenPaaS-Suite/esn-frontend-contacts/blob/02db0a636eed4935e3901206615586f9a546734d/src/linagora.esn.dav.import/app/common/dav-import-api-client.service.js#L8

Previously, in the old codebase, there was a separate `linagora.esn.dav.import` repository to do that: https://github.com/linagora/linagora.esn.dav.import/blob/6711eb0a0610d33599479aa7a837330d697e1598/frontend/app/import/dav-import.service.js#L7 (because it is required in both `linagora.esn.contacts` and `linagora.esn.calendar`).

So I suggest that we either move `linagora.esn.dav.import` to a separate repository or move it to somewhere in `esn-frontend-common-libs`. Wdyt @MichaelBailly @tuanlc @piavgh?

**Comment by tuanlc** [comment]
Yes, agree. But from what I know `linagora.esn.dav.import` only contains common services to import, so how about having a dedicated library for it.

**Comment by huy-ta** [comment]
> Yes, agree. But from what I know `linagora.esn.dav.import` only contains common services to import, so how about having a dedicated library for it.

Yes, agree. That's also what I meant:

> I suggest that we either move linagora.esn.dav.import to a separate repository

**Comment by piavgh** [comment]
A separate library is better. `esn-frontend-common-libs` is so big already :D
