### ISSUE TITLE
Attendee calendar does not update when event is created using DAV

### ISSUE THREAD

**Issue by MichaelBailly** [OpenPaaS-Suite/esn-frontend-calendar#78]
**Reproduction steps**

User1 & User2 are two OpenPaaS calendar user.

* user2 opens its calendar grid on a browser
* user1 synchronizes its calendar using DavX5 on Android
* user1 creates an event event1, invites user2, validates

**Current behaviour**

event1 is not displayed on user2 calendar. If user2 refreshes, event1 is displayed

**Expected behaviour**

event1 is displayed on user2 calendar.

**Comment by piavgh** [comment]
@MichaelBailly : I can reproduce this issue in my localhost with v1.8.0 (before splitting), but I think it's not an issue from ESN

The issue is caused by DavX5, which doesn't synchronize immediately after creating an event. If you manually synchronize DavX5 (by pressing the button), ESN will receive the message and update the UI correctly.

On some devices, we even have this issue https://www.davx5.com/faq/synchronization-is-not-run-as-expected

#### How to fix this
1. On default, The DavX5 Calendars sync. interval is "Every 4 hours". You can change it to "Every 15 minutes" like in the image below:

![davx5-interval](https://user-images.githubusercontent.com/4060207/92567753-586a2400-f2a8-11ea-9372-e92bf52753aa.png)

With this option, the calendar event will be synchronized by DavX5 much faster (about 1 minute in my localhost)

2. You can press the Synchronize button manually any time after creating an event (users will not likely to do this)

But either way, this is not something we can fix in ESN
