### ISSUE TITLE
I cannot change my participation status when I am the organizer of an event without having to press the "Save" button

### ISSUE THREAD

**Issue by MichaelBailly** [OpenPaaS-Suite/esn-frontend-calendar#89]
#### Steps to reproduce

This bug only happens on the web app.

- As User1:

1. Go to the web app, login, and go to Calendar.
2. Create an event. (Optionally) Invite User2 and User3.
3. Open the newly created event.
4. Click on the "Maybe" button to change the participation status.

#### Current behaviour

Nothing happens. No notification is shown, and User1's participation status isn't updated. The participation status will only be updated after User1 (the organizer) clicks the "Save" button.

#### Expected behavior

User1's participation status should be updated and a notification should be shown to inform that the participation status has been updated _without_ having to press the "Save" button.

#### Criteria

- [x] The participation status should be updated right after the organizer clicks one of the "Accept/Maybe/Decline" buttons, without having to click the "Save" button.
- [x] If the organizer chooses the same participation status, nothing should happen.
- [x] After the participation status has been updated when the user clicks one of the "Accept/Maybe/Decline" buttons, he/she should be able to continue to edit the event.
- [x] After the organizer has made some changes (but hasn't clicked the "Save" button), and he/she clicks one of the "Accept/Maybe/Decline" buttons, the participation status should be updated _and_ the changes he/she has made must still remain and he/she can save them.
- [x] the save and delete buttons should be disabled while the organizer participation status is being updated ( slow connections ).

**Comment by piavgh** [comment]
I will leave this issue and PR on hold for now until Renaud has available time for explanation

**Comment by huy-ta** [comment]
@piavgh How is it now?

**Comment by tuanlc** [comment]
This is very old behavior. As the new BA of calendar feature, @huy-ta you should provide a suggestion in this case. You can check other calendar systems like Google, Outlook or Thunderbird.

**Comment by huy-ta** [comment]
I'll look into this and provide the expected behaviour so that we can start to work on it.

**Comment by asmaNode** [comment]
@huy-ta i need more information about it

**Comment by huy-ta** [comment]
@asmaNode I have updated the issue. Please make sure the "Additional criteria" must be satisfied.

While investigating the issue, I've found the cause of it (and also the bare solution). Here's the hints:

1. At **src/esn.calendar.libs/app/components/event/form/event-form.controller.js**, line 386 -> 389:

```js
      if (status !== $scope.editedEvent.getOrganizerPartStat()) {
        $scope.editedEvent.setOrganizerPartStat(status);
        $scope.$broadcast(CAL_EVENTS.EVENT_ATTENDEES_UPDATE);
      }
```

This means that when the organizer clicks one of the "Accept/Maybe/Decline" buttons, it doesn't update the participation status immediately, and the organizer will have to press the "Save" button in order to update the participation status.

Therefore, you'll need to change it to something like:

```js
      if (status !== $scope.editedEvent.getOrganizerPartStat()) {
        $scope.editedEvent.setOrganizerPartStat(status);
        $scope.$broadcast(CAL_EVENTS.EVENT_ATTENDEES_UPDATE);

        _changeParticipationAsAttendee();
      }
```

2. At **src/esn.calendar.libs/app/services/event-service.js**, line 503:

```js
    if (!event.changeParticipation(status, emails)) {
      return $q.when(null);
    }
```

The `event.changeParticipation` only works for the attendees of the event, not the organizer. And it should stay that way (meaning you should not modify the `event.changeParticipation` function). What should be changed is that we should check whether it is the organizer or an attendee, and update the participation status accordingly:

```js
    if (event.organizer.email !== emails[0]) {
      if (!event.changeParticipation(status, emails)) {
        return $q.when(null);
      }
    } else {
      event.setOrganizerPartStat(status);
    }
```

**Comment by rezk2ll** [comment]
# Definition of Done

## what I did
I resolved the issue in https://github.com/OpenPaaS-Suite/esn-frontend-calendar/pull/171
## demos
edit the organizer participation without saving the form: https://streamable.com/rq9hal
edit the organizer participation and continue editing and saving the form: https://streamable.com/2n9wpy
edit organizer participation with recurrent events: https://streamable.com/upxz50
disable action forms while updating the partstat: https://streamable.com/l88g6l
## tested on
- OS: Ubuntu 18.04.4 LTS
- Browser: chrome 86.0.4240.111
