### ISSUE TITLE
I cannot save event if change start date by typing date string into start date field

### ISSUE THREAD

**Issue by Trongk58d** [OpenPaaS-Suite/esn-frontend-calendar#93]
# Reproduction steps
Using the web interface
* Create new event, edit start date by typing date string (exp: Thu 2020/09/10)
# Actual behaviour
* Button "save" event is not activated.
* Cannot save event
# Expected behavior
* Can select start date by that way, and event can be save.
# More Infomation
* If I copy this date string and paste to that field, button save work and i can save event.

**Comment by asmaNode** [comment]
The problem here that you  pasted a date with a different dateformat of your calendar  so the save button  will be disabled , for example if your default  langage is english your dateformat will be : 'EEE yyyy/MM/dd' and if it is french it will be in reverse : 'EEE dd/MM/yyyy'

Here is a demo : https://streamable.com/swoaxo

The real issue here is that we must manage all the different dateformat typed by the user and format it with the default format of the user's calendar .
I have started  creating a directive for this . So what I propose is to create new issue fot this but it  still  'nice to have' not a bug
