### ISSUE TITLE
As a user, I want a more user-friendly time picker instead of the current clock picker so that I can conveniently pick time on all types of devices

### ISSUE THREAD

**Issue by fabienmoyon** [OpenPaaS-Suite/esn-frontend-calendar#98]
#### User story summary

As a user, I want a more user-friendly time picker instead of the current clock picker so that I can conveniently pick time on all types of devices.

#### Where to find the feature

The current clock picker is used in many places, notably the event dialog (when you create an event or edit an event in Calendar).

#### Criteria

- [x] The time picker must support both 12-hour format and 24-hour format.
- [x] The step for the time picker is 15 minutes, starting from 12:00 AM (in 12-hour format) or 00:00 (in 24-hour format).
- [x] The currently selected time should be highlighted (by having the primary color) in the list of time options.
- [x] The time picker must respect the selected language (locale) of the user. For example, when the user has selected Vietnamese, it should be **12:00 SA** instead of **12:00 AM**.
- [x] The user will also be able to edit the time directly in the input. This should work with both 12-hour format and 24-hour format.
- [x] When the user enters an invalid time in the input (e.g. "abcdef") and leaves the input, the time resets back to the previous value.
- [x] When 12-hour format is selected and the user inputs a time within [00:00, 12:00], e.g. **09:00**, it should then be converted to **09:00 AM** after the input loses focus.
- [x] When 12-hour format is selected and the user inputs a time within [12:00, 24:00], e.g. **15:00**, it should then be converted to **03:00 PM** after the input loses focus.
- [x] When the user inputs a time larger than 24:00, e.g. **25:00**, it should be considered as an invalid date.
- [x] On mobile devices, the native time picker should be used instead.
- [x] When the user has no permission to edit the event, the time selector should appear disabled.
- [x] When the user enters the time select input using the "Tab" button on the keyboard, it should open the select menu and should close it when the user leaves the input, also using "Tab".
- [ ] (Optional) While the user is inputting, the best matched time option should be selected and the dropdown should scroll to it. For example, when the user inputs "430", the **04:30** (in 24-hour format) or **04:30 AM** (in 12-hour format) will be selected.

#### UI/UX Design

- When the user first opens the time picker:

![image](https://user-images.githubusercontent.com/24670327/94638679-b9fc3c00-0304-11eb-8bc5-6dafc543905b.png)

- The selected time should be highlighted in the list of time options:

![image](https://user-images.githubusercontent.com/24670327/94639584-b36ec400-0306-11eb-8b0c-45a80c660cba.png)

**Comment by chamerling** [comment]
This is not so easy. From what I remember, this component opens this timepicker on desktop and the native one on mobile.
One solution will be to fix the CSS no?

**Comment by fabienmoyon** [comment]
Precisely, we need to simplify by only used native time input in desktop and mobile. For me it's the best way and it's more easy to maintain.
That's really not easy to fix in CSS because at the update or creation of the event, the modal add the modal-backdrop and fixed the position body position..

**Comment by MichaelBailly** [comment]
I'm +1 on working to remove the current clockpicker. GG Calendar for example got a more simple, yet really effective.

**Comment by rezk2ll** [comment]
I've been stuck on this cause using a time input field will always yield errors cause of angularJS validation
```json
Error: [ngModel:datefmt] Expected `"2020-09-16T11:30:00.000Z"` to be a date
```

because angular expects the model to be a `Date` object, but the shared model ( between the date and time fields ) is a moment object.

so this needs a new directive to handle this issue and add the support of `moment` object in the time input field.

some plnkr about this: https://embed.plnkr.co/plunk/I87YcH

**Comment by MichaelBailly** [comment]
Be careful that the event can be created out of the web frontend. I mean: 
- usera configures its calendar on thunderbird
- on thunderbird, create an event tomorrow at 10:18
- now open it in the web frontend. What happens? Does it react correctly ?

**Comment by huy-ta** [comment]
I have written the detailed user story. Please make sure to check out the criteria @rezk2ll.

**Comment by MichaelBailly** [comment]
> On mobile devices, the native time picker should be used instead.

That may be easy, or hard. If that's not easy, better ship a first version with HTML time picker, and take the time to enhance it afterwards.

**Comment by rezk2ll** [comment]
@huy-ta for this point:

`When the user enters an invalid time in the input (e.g. "abcdef"), the input should be switched to the error state (red underline), and then the time resets back to the previous value.`

we can't really set the input in an error state since the `active` class will just override the bootstrap `has-error` class and the red underline will be hidden under the blue active state line.

other than that the validation works correctly and the input resets back to the previous valid state on blur.

**Comment by huy-ta** [comment]
> @huy-ta for this point:
> 
> `When the user enters an invalid time in the input (e.g. "abcdef"), the input should be switched to the error state (red underline), and then the time resets back to the previous value.`
> 
> we can't really set the input in an error state since the `active` class will just override the bootstrap `has-error` class and the red underline will be hidden under the blue active state line.
> 
> other than that the validation works correctly and the input resets back to the previous valid state on blur.

OK let's change it to `When the user enters an invalid time in the input (e.g. "abcdef") and leaves the input, the input should be switched to the error state (red underline), and then the time resets back to the previous value.`, which is what we're currently doing.

**Comment by rezk2ll** [comment]
@huy-ta `the input should be switched to the error state (red underline)` is not possible because of the default style applied to focused input ( blue underline )

**Comment by huy-ta** [comment]
> @huy-ta `the input should be switched to the error state (red underline)` is not possible because of the default style applied to focused input ( blue underline )

I see that it's working for the current input:

![image](https://user-images.githubusercontent.com/24670327/94903011-50765c00-04c3-11eb-8fff-295eaa76e6f5.png)

**Comment by rezk2ll** [comment]
when the user leaves the input the validation happens, so if the time is not valid it will be reset back to a valid state ( previous time ) so you will not see the red underline. ( in the new component )

**Comment by rezk2ll** [comment]
# Definition of done

**What I did**:
- I resolved this issue in https://github.com/OpenPaaS-Suite/esn-frontend-calendar/pull/146, now when creating or editing an event in the `calendar` SPA a new time select component should appear instead of the old clock picker component and should allow the user to modify and set the event time.

- demo:  https://streamable.com/4j0z2y

**used environment**:
- local `esn-frontend-calendar` SPA and https://dev.open-paas.org/ as backend.
- browser: chrome `85.0.4183.121`
- OS: `Ubuntu 18.04.4 LTS`

**Comment by tlle14** [comment]
Hi @huy-ta @rezk2ll 

Time picker works normally unless 2 minor issues. I will create tickets for them.

1. Time picker hasn't been updated on the Invitation mail when the attendee wants to propose a new time:
![image](https://user-images.githubusercontent.com/69950655/95298298-1089ed00-08a6-11eb-8abf-83066d820a9b.png)

2. System doesn't accept manual input "SA/CH" (AM/PM in Vietnamese) in the time textbox
![Peek 2020-10-07 12-13](https://user-images.githubusercontent.com/69950655/95298883-fa306100-08a6-11eb-927d-016773148ca2.gif)

**Comment by huy-ta** [comment]
Thank you @tlle14. When you have created the issues, please add them to the top of the backlog of **Calendar & Contacts #1**.

**Comment by tlle14** [comment]
Hi @huy-ta 
Please check these issues on Mobile:
https://github.com/OpenPaaS-Suite/esn-frontend-calendar/issues/199
https://github.com/OpenPaaS-Suite/esn-frontend-calendar/issues/200

**Comment by rezk2ll** [comment]
# Definition of Done

## Done
- [x] The time picker must support both 12-hour format and 24-hour format.
- [x] The step for the time picker is 15 minutes, starting from 12:00 AM (in 12-hour format) or 00:00 (in 24-hour format).
- [x] The currently selected time should be highlighted (by having the primary color) in the list of time options.
- [x] The time picker must respect the selected language (locale) of the user. For example, when the user has selected Vietnamese, it should be **12:00 SA** instead of **12:00 AM**.
- [x] The user will also be able to edit the time directly in the input. This should work with both 12-hour format and 24-hour format.
- [x] When the user enters an invalid time in the input (e.g. "abcdef") and leaves the input, the time resets back to the previous value.
- [x] When 12-hour format is selected and the user inputs a time within [00:00, 12:00], e.g. **09:00**, it should then be converted to **09:00 AM** after the input loses focus.
- [x] When 12-hour format is selected and the user inputs a time within [12:00, 24:00], e.g. **15:00**, it should then be converted to **03:00 PM** after the input loses focus.
- [x] When the user inputs a time larger than 24:00, e.g. **25:00**, it should be considered as an invalid date.
- [x] On mobile devices, the native time picker should be used instead.
- [x] when the user has no permission to edit the event, the time selector should appear disabled
- [x] when the user enters the time select input using the keyboard ( `Tab` ) it should open the select menu and should close it when the user leaves the input.

## Won't do
- [ ] (Optional) While the user is inputting, the best matched time option should be selected and the dropdown should scroll to it. For example, when the user inputs "430", the 04:30 (in 24-hour format) or 04:30 AM (in 12-hour format) will be selected.
